modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Traverse-Joe/Baubley-Heart-Canisters/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="Thanks goes to UpcraftLP who helped with original build. Also Abused_Master for helping when i bugged him."
authors="${mod_authors}"
description='''
{mod_description}
'''

[[dependencies.bhc]]
    modId="neoforge"
    type = "required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"